// <auto-generated />
using System;
using CrixusJa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrixusJa.Migrations
{
    [DbContext(typeof(Datacontext))]
    partial class DatacontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrixusJa.Data.User", b =>
                {
                    b.Property<string>("username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("username");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            username = "mgenius",
                            createdat = new DateTime(2022, 11, 8, 21, 47, 8, 660, DateTimeKind.Local).AddTicks(8966),
                            password = "password"
                        },
                        new
                        {
                            username = "crixus",
                            createdat = new DateTime(2022, 11, 8, 21, 47, 8, 660, DateTimeKind.Local).AddTicks(8976),
                            password = "international"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
